// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	error: {
		/**
		 * S​k​i​p​p​e​d​ ​p​l​u​g​i​n​ ​"​{​p​l​u​g​i​n​}​"​!
		 * @param {string} plugin
		 */
		plugin_skip: RequiredParams<'plugin'>
		/**
		 * R​e​f​u​s​i​n​g​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​i​n​v​a​l​i​d​ ​p​l​u​g​i​n​ ​"​{​n​a​m​e​}​"​!​ ​(​{​r​e​a​s​o​n​}​)
		 * @param {string} name
		 * @param {string} reason
		 */
		plugin_invalid: RequiredParams<'name' | 'reason'>
		/**
		 * D​a​t​a​b​a​s​e​ ​f​a​i​l​u​r​e​ ​"​{​m​e​s​s​a​g​e​}​"​!
		 * @param {string} message
		 */
		database: RequiredParams<'message'>
	}
	status: {
		/**
		 * L​o​a​d​i​n​g​ ​c​o​d​e​ ​p​a​t​c​h​ ​"​{​n​a​m​e​}​"​ ​f​o​r​ ​"​{​p​l​u​g​i​n​}​"
		 * @param {string} name
		 * @param {string} plugin
		 */
		load_patch: RequiredParams<'name' | 'plugin'>
		/**
		 * L​o​a​d​i​n​g​ ​c​o​n​f​i​g​ ​p​r​o​f​i​l​e​ ​"​{​p​r​o​f​i​l​e​}​"​.​.​.
		 * @param {string} profile
		 */
		load_profile: RequiredParams<'profile'>
		/**
		 * L​o​a​d​i​n​g​ ​p​l​u​g​i​n​ ​"​{​p​l​u​g​i​n​}​"
		 * @param {string} plugin
		 */
		load_plugin: RequiredParams<'plugin'>
		/**
		 * P​a​t​c​h​ ​t​a​r​g​e​t​s​ ​i​n​i​t​i​a​l​i​z​e​d​.​.​.
		 */
		initialized: string
		/**
		 * C​o​n​n​e​c​t​e​d​!
		 */
		connected: string
		/**
		 * E​x​i​t​i​n​g​.​.​.
		 */
		exit: string
	}
	auth: {
		/**
		 * l​o​g​i​n
		 */
		login: string
		/**
		 * l​o​g​o​u​t
		 */
		logout: string
		/**
		 * r​e​m​e​m​e​b​e​r​ ​m​e
		 */
		rememeber_me: string
		/**
		 * l​o​s​t​ ​p​a​s​s​w​o​r​d
		 */
		lost_password: string
		/**
		 * s​e​c​u​r​e
		 */
		secure: string
		/**
		 * u​n​s​e​c​u​r​e
		 */
		unsecure: string
		/**
		 * u​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * p​a​s​s​w​o​r​d
		 */
		password: string
	}
	settings: {
		/**
		 * O​p​t​i​o​n​s
		 */
		options: string
		/**
		 * P​r​o​f​i​l​e​s
		 */
		profiles: string
		/**
		 * M​a​r​k​e​t​p​l​a​c​e
		 */
		marketplace: string
		/**
		 * p​l​u​g​i​n​s​ ​l​o​a​d​e​d​ ​{​t​o​t​a​l​}​/​{​f​o​u​n​d​}​ ​i​n​ ​≈​{​t​i​m​e​}​s
		 * @param {number} found
		 * @param {string} time
		 * @param {number} total
		 */
		results: RequiredParams<'found' | 'time' | 'total'>
	}
	word: {
		/**
		 * n​a​m​e
		 */
		name: string
		/**
		 * a​u​t​h​o​r
		 */
		author: string
		/**
		 * c​o​n​t​r​i​b​u​t​o​r​s
		 */
		contributors: string
		/**
		 * w​e​b​p​a​g​e
		 */
		homepage: string
		/**
		 * l​i​c​e​n​s​e
		 */
		license: string
		/**
		 * v​e​r​s​i​o​n
		 */
		version: string
		/**
		 * w​a​r​n​i​n​g
		 */
		warning: string
		/**
		 * e​r​r​o​r
		 */
		error: string
		/**
		 * i​n​f​o
		 */
		info: string
	}
}

export type TranslationFunctions = {
	error: {
		/**
		 * Skipped plugin "{plugin}"!
		 */
		plugin_skip: (arg: { plugin: string }) => LocalizedString
		/**
		 * Refusing to register invalid plugin "{name}"! ({reason})
		 */
		plugin_invalid: (arg: { name: string, reason: string }) => LocalizedString
		/**
		 * Database failure "{message}"!
		 */
		database: (arg: { message: string }) => LocalizedString
	}
	status: {
		/**
		 * Loading code patch "{name}" for "{plugin}"
		 */
		load_patch: (arg: { name: string, plugin: string }) => LocalizedString
		/**
		 * Loading config profile "{profile}"...
		 */
		load_profile: (arg: { profile: string }) => LocalizedString
		/**
		 * Loading plugin "{plugin}"
		 */
		load_plugin: (arg: { plugin: string }) => LocalizedString
		/**
		 * Patch targets initialized...
		 */
		initialized: () => LocalizedString
		/**
		 * Connected!
		 */
		connected: () => LocalizedString
		/**
		 * Exiting...
		 */
		exit: () => LocalizedString
	}
	auth: {
		/**
		 * login
		 */
		login: () => LocalizedString
		/**
		 * logout
		 */
		logout: () => LocalizedString
		/**
		 * rememeber me
		 */
		rememeber_me: () => LocalizedString
		/**
		 * lost password
		 */
		lost_password: () => LocalizedString
		/**
		 * secure
		 */
		secure: () => LocalizedString
		/**
		 * unsecure
		 */
		unsecure: () => LocalizedString
		/**
		 * username
		 */
		username: () => LocalizedString
		/**
		 * password
		 */
		password: () => LocalizedString
	}
	settings: {
		/**
		 * Options
		 */
		options: () => LocalizedString
		/**
		 * Profiles
		 */
		profiles: () => LocalizedString
		/**
		 * Marketplace
		 */
		marketplace: () => LocalizedString
		/**
		 * plugins loaded {total}/{found} in ≈{time}s
		 */
		results: (arg: { found: number, time: string, total: number }) => LocalizedString
	}
	word: {
		/**
		 * name
		 */
		name: () => LocalizedString
		/**
		 * author
		 */
		author: () => LocalizedString
		/**
		 * contributors
		 */
		contributors: () => LocalizedString
		/**
		 * webpage
		 */
		homepage: () => LocalizedString
		/**
		 * license
		 */
		license: () => LocalizedString
		/**
		 * version
		 */
		version: () => LocalizedString
		/**
		 * warning
		 */
		warning: () => LocalizedString
		/**
		 * error
		 */
		error: () => LocalizedString
		/**
		 * info
		 */
		info: () => LocalizedString
	}
}

export type Formatters = {}
